# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'WhatsBirds' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'TensorFlowLiteSwift'
  pod 'RosaKit'
  # Pods for WhatsBirds

  target 'WhatsBirdsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WhatsBirdsUITests' do
    # Pods for testing
  end

  
end
